2017-05-05 20:39:42.854 [error] <0.631.0> Supervisor received unexpected message: {gen_event_EXIT,{partisan_peer_service_events,#Ref<0.0.2.249>},shutdown}
2017-05-05 20:41:29.499 [error] <0.4046.0> Supervisor partisan_pool had child {partisan_peer_service_server,undefined,undefined,undefined} started with {partisan_peer_service_server,acceptor_init,undefined} at 1 exit with reason noproc in context shutdown_error
2017-05-05 20:41:46.112 [error] <0.4878.0> gen_server lasp_distribution_backend terminated with reason: no function clause matching lasp_core:update(<<174,84,20,123,124,18,55,68,39,66,108,178,227,29,12,102,29,88,3,27>>, orset, a, #Fun<lasp_distribution_backend.35.132945558>, #Fun<lasp_distribution_backend.36.132945558>, <0.4880.0>) line 430
2017-05-05 20:41:46.112 [error] <0.4878.0> CRASH REPORT Process lasp_distribution_backend with 2 neighbours exited with reason: no function clause matching lasp_core:update(<<174,84,20,123,124,18,55,68,39,66,108,178,227,29,12,102,29,88,3,27>>, orset, a, #Fun<lasp_distribution_backend.35.132945558>, #Fun<lasp_distribution_backend.36.132945558>, <0.4880.0>) line 430 in gen_server:terminate/7 line 812
2017-05-05 20:41:46.112 [error] <0.4811.0> Supervisor lasp_sup had child lasp_distribution_backend started with lasp_distribution_backend:start_link() at <0.4878.0> exit with reason no function clause matching lasp_core:update(<<174,84,20,123,124,18,55,68,39,66,108,178,227,29,12,102,29,88,3,27>>, orset, a, #Fun<lasp_distribution_backend.35.132945558>, #Fun<lasp_distribution_backend.36.132945558>, <0.4880.0>) line 430 in context child_terminated
