2017-05-05 21:02:50.898 [error] <0.631.0> Supervisor received unexpected message: {gen_event_EXIT,{partisan_peer_service_events,#Ref<0.0.1.5848>},shutdown}
2017-05-05 21:04:56.136 [error] <0.4875.0> gen_server lasp_distribution_backend terminated with reason: no function clause matching lasp_core:update(<<174,84,20,123,124,18,55,68,39,66,108,178,227,29,12,102,29,88,3,27>>, orset, <0.4764.0>, #Fun<lasp_distribution_backend.35.132945558>, #Fun<lasp_distribution_backend.36.132945558>, <0.4877.0>) line 430
2017-05-05 21:04:56.137 [error] <0.4875.0> CRASH REPORT Process lasp_distribution_backend with 2 neighbours exited with reason: no function clause matching lasp_core:update(<<174,84,20,123,124,18,55,68,39,66,108,178,227,29,12,102,29,88,3,27>>, orset, <0.4764.0>, #Fun<lasp_distribution_backend.35.132945558>, #Fun<lasp_distribution_backend.36.132945558>, <0.4877.0>) line 430 in gen_server:terminate/7 line 812
2017-05-05 21:04:56.137 [error] <0.4808.0> Supervisor lasp_sup had child lasp_distribution_backend started with lasp_distribution_backend:start_link() at <0.4875.0> exit with reason no function clause matching lasp_core:update(<<174,84,20,123,124,18,55,68,39,66,108,178,227,29,12,102,29,88,3,27>>, orset, <0.4764.0>, #Fun<lasp_distribution_backend.35.132945558>, #Fun<lasp_distribution_backend.36.132945558>, <0.4877.0>) line 430 in context child_terminated
